sudo: false
#notifications:
#  slack:
#    secure: NxhzhKGYnZYZiWVZM4w1PlZpTy9bbmNlvbqjL+9d4PvK4hFzPwQU12CchhBPeXNGLWBHg/ti6Scn/t5XIS3YJrkk4ydWmJBht5UId8uFZ1A7GCUnNNPTt2RG55lbJJdZSj01rOGZjEQbE5RyckEjgRzhZjdZ+HsjoPaRzWIBrvE=
language: php
php:
- '5.6'
- '7.0'
env:
- coverage="--coverage"
- coverage=""
matrix:
  exclude:
  - php: '7.0'
    env: coverage="--coverage"
  allow_failures:
  - env: coverage="--coverage"
  - php: '7.0'
  fast_finish: true
cache:
  directories:
  - "$HOME/.composer/cache"
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE ushahidi;'
- cp .env.travis .env
install:
- composer install --no-interaction
before_script:
- composer pre-test
- php -S localhost:8000 -t httpdocs httpdocs/index.php &
- mysql -e 'SET @@GLOBAL.wait_timeout=1800'
script:
- if [ "${coverage}" == "" ]; then composer test; fi
- if [ "${coverage}" != "" ]; then composer coverage; fi
- composer lint
after_success:
- if [ "${coverage}" != "" ]; then travis_retry bin/coveralls -v; fi
### Deploy files now generated by Codeship
# before_deploy:
# - bin/release ${TRAVIS_TAG:-$TRAVIS_COMMIT}
# deploy:
# - provider: releases
#   api_key:
#     secure: C9dRB0X6/QWeKMIdDnuItGzzcJITf5oeGSd/Ry85//DawkC1nZn7yhjOFJuzOT1W8+lrmYgOtqVWaZdKuw36CEa4iooXCwDqn+6SWL1N/Q0JkJZH/pXkjSjtkfRV9iNlSRw3DF1yAcout1piqbD4BKDcAtrIf5apGQnXGzKjn/Q=
#   file: build/*
#   file_glob: true
#   skip_cleanup: true
#   on:
#     repo: ushahidi/platform
#     php: 5.5
#     tags: true
#     all_branches: true
